name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: make all

    - name: check generated
      run: |
        [ -n "$(git status --porcelain=v1 2>/dev/null)" ] && exit 1

    - name: image
      run: make image
