name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  # use a pinned image to generate the eBPF code
  TAG_GENERATE_IMAGE: "a71424e"

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Install test dependencies
      run: sudo apt-get -y install bats ncat

    - name: enable IP forwarding
      run: |
        sudo sysctl -w net.ipv4.ip_forward=1

    - uses: actions/checkout@v2

    - name: build
      run: make all

    - name: verify
      run: make verify

    - name: image
      run: make image

    - name: test
      run: |
        cd tests
        bats tests.bats

    - name: debug failures
      if: failure()
      run: |
        sudo ps axf
        sudo ip netns
        sudo ip route
        sudo ss -apn
