name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Setup BATS
      run: apt-get -y install bats

    - uses: actions/checkout@v2

    - name: build
      run: make all

    - name: check generated
      run: |
        git status --porcelain=v1
        if [[ $(git status --porcelain) ]]; then
          exit 1
        fi

    - name: image
      run: make image

    - name: test
      run: |
        export TERM=dumb
        make test
